name: googlemap
description: Location by Voice application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.3.0
  flutter_tts: ^3.0.3
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  custom_info_window: ^1.0.1
  geolocator: ^10.1.0
  flutter_geocoder: ^0.2.2-nullsafety
  geocoding: ^2.0.4
  flutter_polyline_points: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  uuid: ^4.2.1
  http:
  google_fonts:
  geocode: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


